In [1]:
import numpy as np
from numpy.linalg import cond, norm
from scipy.linalg import hilbert, lu_factor, lu_solve 

In [2]:
n=5
H = hilbert(n)
print(H)

[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]


In [3]:
cond(H, p=np.inf) # default is using 2-norm, computed with SVD

943655.9999995853

In [5]:
# problem with known solution 
xTrue = np.ones(n) # true value of x
b = H @ xTrue      # with roundoff error order 1e-16

# LU decomposition with partial pivoting
lu, piv = lu_factor(H)
xApprox = lu_solve((lu, piv), b)
print(xApprox-xTrue)
print(norm(xApprox-xTrue))

[-9.32587341e-15  6.03961325e-14  3.50830476e-14 -3.60156349e-13
  2.86215496e-13]
4.654002479964031e-13


In [8]:
def TestHilbert(n):
    H = hilbert(n)
    print("cond(H): ", cond(H, p=np.inf) )
    # problem with known solution 
    xTrue = np.ones(n) # true value of x
    b = H @ xTrue      # with roundoff error order 1e-16

    # LU decomposition with partial pivoting
    lu, piv = lu_factor(H)
    xApprox = lu_solve((lu, piv), b)
    #print(xApprox-xTrue)
    print("error: ", norm(xApprox-xTrue)) 

TestHilbert(14)




cond(H):  4.627614644977777e+18
error:  49.822054497190166
