# Homework set 3

Please **submit this Jupyter notebook through Canvas** no later than **Mon Nov. 21, 9:00**. **Submit the notebook file with your answers (as .ipynb file) and a pdf printout. The pdf version can be used by the teachers to provide feedback. A pdf version can be made using the save and export option in the Jupyter Lab file menu.**

Homework is in **groups of two**, and you are expected to hand in original work. Work that is copied from another group will not be accepted.

# Exercise 0
Write down the names + student ID of the people in your group.

Jade Dubbeld, 11692065

Maickel Hartlief, 14015277

Run the following cell to import NumPy and Pyplot.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Exercise 1

In this exercise you will study the accuracy of several methods for computing the QR decomposition. You are asked to implement these methods yourself. (However, when testing your implementation you may compare with an external implementation.)


## (a) 
Implement the classical and modified Gram-Schmidt procedures for computing the QR decomposition.

Include a short documentation using triple quotes: describe at least the input and the output, and whether the code modifies the input matrix.


In [ ]:
def classical_gram_schmidt(A):
    # YOUR CODE HERE
    

def modified_gram_schmidt(A):
    # YOUR CODE HERE

## (b) (a+b 3.5 pts)
Let $H$ be a Hilbert matrix of size $n$ (see Computer Problem 2.6). Study the quality of the QR decompositions obtained using the two methods of part (a), specifically the loss of orthogonality. In order to do so, plot the quantity $\| I - Q^T Q \|$ as a function of $n$ on a log scale. Vary $n$ from $2$ to $12$.



In [ ]:
# YOUR CODE HERE

## (c) (1.5 pts)
Try applying the classical procedure twice. Plot again the loss of orthogonality when computing the QR decomposition of the Hilbert matrix of size $n$ as in (b).


In [ ]:
# YOUR CODE HERE

## (d) (2 pts)
Implement the Householder method for computing the QR decomposition. Remember to include a short documentation.

In [2]:
def householder_qr(A):
    """
    Applying Householder QR decomposition to input matrix A. Returning matrix R and Q.

            Parameters:
                    A (numpy.ndarray): Any matrix of size m x n

            Returns:
                    R (numpy.ndarray): Resulting upper triangular matrix R of size m x n after 
                                         Householder QR decomposition
                    Q (numpy.ndarray): Resulting orthogonal matrix Q of size n x n after 
                                         Householder QR decomposition
    """

    A_original = A
    list_of_Hs = []
    origA_rows = A.shape[0]
    origA_cols = A.shape[1]
    
    # run Householder QR decomposition for all columns in original matrix A
    for i in range(origA_cols):
        rows = A.shape[0]
        cols = A.shape[1]
        
        # get vector a (first column) from current matrix A
        a = np.zeros((rows,1))  
        
        for row in range(len(A)):
            a[row]=(A[row][0])
        
        # calculate length of vector a
        length_a = np.linalg.norm(a,ord=2)
        
        # create vector e with n times 0s and 1 at the top
        e = np.zeros((rows,1))
        e[0] = 1
        
        # compute vector v
        v = a + length_a*e
        
        # compute denominator in formula for H (vT*v)
        denom = 0
        
        for row in range(len(v)):
            denom += v[row]**2

        # calculate values for Householder matrix and append to list
        I = np.identity(len(a))
        H = I - 2/denom * (v*v.T)

        list_of_Hs.append(H)
        
        # multiply Householder matrix with matrix A
        HA = H @ A
        HA = HA.round(decimals=2)

        # generate next matrix A (cut off first column and first row)
        A = np.zeros((rows-1,cols-1))

        for row in range(len(A)):
            A[row]=(HA[row+1][1:])
            
    # broaden Householder matrices to matrix shape of original matrix A with identity matrix
    for i in reversed(range(len(list_of_Hs))):
        H = np.identity(origA_rows)
        H[i: , i: ] = list_of_Hs[i]
        list_of_Hs[i] = H

    # compute upper triangular matrix R
    R = list_of_Hs[-1]
    
    for i in reversed(range(len(list_of_Hs)-1)):
        R = R @ list_of_Hs[i]

    R = R @ A_original
    R = R.round(decimals=2)
    R[R==-0] = 0

    # compute orthogonal matrix Q
    Q = list_of_Hs[0]
    
    for i in range(1,len(list_of_Hs)):
        Q = Q @ list_of_Hs[i]
        
    Q = Q.round(decimals=2)
    Q[Q==-0] = 0
    
    return R,Q

In [3]:
A = np.array([[1, -1, 4],[1, 4, -2],[1, 4, 2],[1, -1, 0]])

R, Q = householder_qr(A)
print(f"matrix R:\n{R}")
print()
print(f"matrix Q:\n{Q}")

matrix R:
[[-2. -3. -2.]
 [ 0. -5.  2.]
 [ 0.  0. -4.]
 [ 0.  0.  0.]]

matrix Q:
[[-0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5  0.5]
 [-0.5  0.5  0.5  0.5]]


## (e) (2 pts)
Perform the analysis of (b) for the Householder method. Discuss the differences between all the methods you have tested so far. Look online and/or in books for information about the accuracy of the different methods and include this in your explanations (with reference).


**Copy of exercise (b):**
\
Let $H$ be a Hilbert matrix of size $n$ (see Computer Problem 2.6). Study the quality of the QR decompositions obtained using the two methods of part (a), specifically the loss of orthogonality. In order to do so, plot the quantity $\| I - Q^T Q \|$ as a function of $n$ on a log scale. Vary $n$ from $2$ to $12$.

In [4]:
def generate_Hilbert(n):
    """
    Create Hilbert matrix as in Computer Problem 2.6

            Parameters:
                    n (int): number of rows/columns of square Hilbert matrix

            Returns:
                    H (numpy.ndarray): Hilbert matrix
    """
    H = np.ones((n,n))

    num_i = 0
    for i in range(n):
        for j in range(n):
            if i == 0 and j == 0:
                H[i,j] = 1
            else:
                H[i,j] = 1/(num_i+j+1)
        num_i += 1
    return H

In [5]:
Hilbert = generate_Hilbert(4)
print(Hilbert)

[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]


In [6]:
n = np.arange(2,13)

for i in n:
    Hilbert = generate_Hilbert(i)
    R, Q = householder_qr(Hilbert)
    print(f"matrix R:\n{R}\n")
    print(f"matrix Q:\n{Q}\n")

    I = np.identity(i)
    norm = np.linalg.norm(I - Q.T @ Q)
    print(f"norm: {norm}\n\n")

matrix R:
[[-1.12 -0.6 ]
 [ 0.   -0.07]]

matrix Q:
[[-0.89  0.45]
 [-0.45 -0.89]]

norm: 0.007636753236814657


matrix R:
[[-1.17 -0.64 -0.45]
 [ 0.   -0.1  -0.11]
 [ 0.    0.   -0.01]]

matrix Q:
[[-0.86  0.51 -0.1 ]
 [-0.43 -0.59  0.68]
 [-0.29 -0.63 -0.72]]

norm: 0.014482057864820092


matrix R:
[[-1.19 -0.67 -0.47 -0.37]
 [ 0.   -0.12 -0.13 -0.12]
 [ 0.    0.   -0.01 -0.01]
 [ 0.    0.    0.   -0.01]]

matrix Q:
[[-0.84  0.52 -0.07 -0.14]
 [-0.42 -0.46  0.56  0.55]
 [-0.28 -0.5  -0.8   0.19]
 [-0.21 -0.52  0.2  -0.8 ]]

norm: 0.01679940475135949


matrix R:
[[-1.21 -0.69 -0.49 -0.39 -0.32]
 [ 0.   -0.13 -0.14 -0.13 -0.12]
 [ 0.    0.    0.   -0.01 -0.01]
 [ 0.    0.    0.    0.   -0.01]
 [  nan   nan   nan   nan   nan]]

matrix Q:
[[-0.83  0.53 -0.14 -0.04   nan]
 [-0.41 -0.34  0.67 -0.06   nan]
 [-0.28 -0.46 -0.47  0.68   nan]
 [-0.21 -0.48  0.24 -0.02   nan]
 [-0.17 -0.41 -0.5  -0.73   nan]]

norm: nan


matrix R:
[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan 

/var/folders/zb/qwtwsp1d539dg2nj7t84r7mc0000gn/T/ipykernel_72735/4229765921.py:58: RuntimeWarning: divide by zero encountered in true_divide
  H = I - 2/denom * (v*v.T)
/var/folders/zb/qwtwsp1d539dg2nj7t84r7mc0000gn/T/ipykernel_72735/4229765921.py:58: RuntimeWarning: invalid value encountered in multiply
  H = I - 2/denom * (v*v.T)
